# Generated by Django 5.2.1 on 2025-05-19 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('goal', models.CharField(max_length=255, verbose_name='Цель')),
                ('deadline', models.DateTimeField(verbose_name='Сроки выполнения')),
                ('budget', models.FloatField(verbose_name='Бюджет')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Контактная информация')),
                ('interaction_history', models.TextField(verbose_name='История взаимодействий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('deadline', models.DateTimeField(verbose_name='Сроки выполнения')),
                ('budget', models.FloatField(verbose_name='Бюджет')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_metrics', models.TextField(verbose_name='Показатель эффективности')),
                ('financial_flow', models.TextField(verbose_name='Движение денежных средств')),
                ('conclusions', models.TextField(verbose_name='Выводы и рекомендации')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.campaign', verbose_name='Кампания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client', verbose_name='Клиент')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project', verbose_name='Проект')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
